---
- name: Verifica e installa Jenkins e Docker su Ubuntu
  hosts: all
  become: yes
  tasks:

    - name: Aggiorna la cache dei pacchetti APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installa dipendenze per repository APT
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Aggiungi la chiave GPG di Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Aggiungi repository Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present
        filename: docker

    - name: Aggiorna la cache dopo aggiunta repo Docker
      apt:
        update_cache: yes

    - name: Installa Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Avvia e abilita Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Aggiungi l'utente corrente al gruppo docker (opzionale)
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Installa Java 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Aggiungi la chiave GPG di Jenkins
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Aggiungi il repository Jenkins
      apt_repository:
        repo: "deb https://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Aggiorna la cache dopo aggiunta repo Jenkins
      apt:
        update_cache: yes

    - name: Installa Jenkins
      apt:
        name: jenkins
        state: present

    - name: Avvia e abilita Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Imposta permessi su /var/lib/jenkins
      file:
        path: /var/lib/jenkins
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'

    - name: Assicurati che il gruppo docker esista
      group:
        name: docker
        state: present

    - name: Aggiungi utente jenkins al gruppo docker
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Cambia permessi socket docker sul host
      file:
        path: /var/run/docker.sock
        group: docker
        mode: '0660'

    - name: Riavvia Jenkins service (non container)
      service:
        name: jenkins
        state: restarted

    - name: Avvia un container Docker registry
      community.docker.docker_container:
        name: registry
        image: registry:2
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"
