---
- name: Setup di un Docker Registry
  hosts: localhost
  become: true
  tasks:

    # Avvia il registry su porta 5000
    - name: Avvia un container Docker registry
      community.docker.docker_container:
        name: registry
        image: registry:2
        state: started
        restart_policy: always
        published_ports:
          - 5000:5000
